version: '3'
services:
  read:
    container_name: read
    build:
      context: ./ReadModel
      dockerfile: ./Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATA_MONGODB_HOST: mongo_read_model
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: read_model
    ports:
      - "8081:8080"
      - "5081:5005"
    depends_on:
      - mongo_read_model
    networks:
      - my-network
  mongo_read_model:
    container_name: mongo_read_model
    image: mongo:7.0.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: read_model
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - my-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_AUTH_DATABASE: read_model
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo_read_model:27017/
    networks:
      - my-network
volumes:
  db:
networks:
  my-network:
    driver: bridge